MyElearningProject/Controllers/InstructorAnalysisController.cs
using MyElearningProject.DAL.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyElearningProject.Controllers
{
    public class InstructorAnalysisController : Controller
    {
        ELearningContext context = new ELearningContext();
        // GET: InstructorAnalysis
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult InstructorPanelPartial(int id)
        {
            id = 1;
            var values = context.Instructors.Where(x=>x.InstructorID==id).ToList();
            var v1 = context.Instructors.Where(x => x.Name == "Ahmet" && x.Surname == "Ölçen").Select(y => y.InstructorID).FirstOrDefault();
            ViewBag.courseCount = context.Courses.Where(x => x.InstructorID == 5).Count();
            var v2 = context.Courses.Where(x => x.InstructorID == v1).Select(y => y.CourseID).ToList();


            ViewBag.commentCount = context.Comments.Where(x => v2.Contains(x.CourseID)).Count();


            return PartialView(values);

        }
        public PartialViewResult CommentPartial()
        {
            //Select InstructorID from Instructors where Name='Ahmet' and Surname ='Ölçen'
            var v1 = context.Instructors.Where(x => x.Name == "Ahmet" && x.Surname == "Ölçen").Select(y => y.InstructorID).FirstOrDefault();
            //Select CourseID From Courses Where InstructorID = 

            var v2 =context.Courses.Where(x=>x.InstructorID==v1).Select(y=>y.CourseID).ToList();
            
            //select * from Comments Where CourseID In
            var v3 = context.Comments.Where(x => v2.Contains(x.CourseID)).ToList();


            return PartialView(v3);
        }

        public PartialViewResult CourseListByInstructor()
        {
            var values = context.Courses.Where(x => x.InstructorID == 5).ToList();
            return PartialView(values);


        }
    }
}

MyElearningProject/Views/InstructorAnalysis/CommentPartial.cshtml
@model List<MyElearningProject.DAL.Entities.Comment> 
<div class="tab-pane active" id="home" role="tabpanel">
    <div class="card-block">
        <div class="profiletimeline">
            @foreach (var item in Model)
            {
                <div class="sl-item">
                    <div class="sl-left"> <img src="~/Templates/material-lite-master/assets/images/users/3.jpg" alt="user" class="img-circle"> </div>
                    <div class="sl-right">
                        <div>
                            <a href="#" class="link">@item.Student.Name @item.Student.Surname</a> <span class="sl-date">@item.Course.Title @item.CommentDate</span>
                            <p class="m-t-10"> @item.CommentText</p>
                        </div>
                    </div>
                </div>
                <hr>
            }


        </div>
    </div>
</div>

MyElearningProject/Views/InstructorAnalysis/CourseListByInstructor.cshtml
@model List<MyElearningProject.DAL.Entities.Course>

<div class="tab-pane" id="settings" role="tabpanel">
    <div class="card-block">
        @foreach (var item in Model)
        {

        <div class="sl-item">
            <div class="sl-left"> </div>
            <div class="sl-right">
                <div>
                    <a href="#" class="link">@item.Instructor.Name @item.Instructor.Surname</a> <span class="sl-date">@item.Duration Dakika</span>
                    <div class="m-t-20 row">
                        <div class="col-md-3 col-xs-12"><img src="@item.ImageUrl" alt="user" class="img-responsive radius"></div>
                        <div class="col-md-9 col-xs-12">
                            <p> @item.CourseDescription </p> <a href="#" class="btn btn-success"> Kursa Git</a>
                        </div>
                    </div>
                    <div class="like-comm m-t-20"> <a href="javascript:void(0)" class="link m-r-10">0 Yorum </a> <a href="javascript:void(0)" class="link m-r-10"><i class="fa fa-heart text-danger"></i> 4.7 Puan</a> </div>
                </div>
            </div>
        </div>
        <hr>
        }
    </div>
</div>

MyElearningProject/Views/InstructorAnalysis/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="row">
    <!-- Column -->
@Html.Action("InstructorPanelPartial","InstructorAnalysis")
    <div class="col-lg-8 col-xlg-9 col-md-7">
        <div class="card">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs profile-tab" role="tablist">
                <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Yorumlar</a> </li>
                <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile" role="tab">İletişim</a> </li>
                <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#settings" role="tab">Kurs Listesi</a> </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
@Html.Action("CommentPartial","InstructorAnalysis")
                <!--second tab-->
                <div class="tab-pane" id="profile" role="tabpanel">
                    <div class="card-block">
                        <div class="row">
                            <div class="col-md-3 col-xs-6 b-r">
                                <strong>Full Name</strong>
                                <br>
                                <p class="text-muted">Johnathan Deo</p>
                            </div>
                            <div class="col-md-3 col-xs-6 b-r">
                                <strong>Mobile</strong>
                                <br>
                                <p class="text-muted">(123) 456 7890</p>
                            </div>
                            <div class="col-md-3 col-xs-6 b-r">
                                <strong>Email</strong>
                                <br>
                                <p class="text-muted">johnathan@admin.com</p>
                            </div>
                            <div class="col-md-3 col-xs-6">
                                <strong>Location</strong>
                                <br>
                                <p class="text-muted">London</p>
                            </div>
                        </div>
                        <hr>
                        <p class="m-t-30">Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</p>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries </p>
                        <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        <h4 class="font-medium m-t-30">Skill Set</h4>
                        <hr>
                        <h5 class="m-t-30">Wordpress <span class="pull-right">80%</span></h5>
                        <div class="progress">
                            <div class="progress-bar bg-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%; height:6px;"> <span class="sr-only">50% Complete</span> </div>
                        </div>
                        <h5 class="m-t-30">HTML 5 <span class="pull-right">90%</span></h5>
                        <div class="progress">
                            <div class="progress-bar bg-info" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%; height:6px;"> <span class="sr-only">50% Complete</span> </div>
                        </div>
                        <h5 class="m-t-30">jQuery <span class="pull-right">50%</span></h5>
                        <div class="progress">
                            <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:50%; height:6px;"> <span class="sr-only">50% Complete</span> </div>
                        </div>
                        <h5 class="m-t-30">Photoshop <span class="pull-right">70%</span></h5>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%; height:6px;"> <span class="sr-only">50% Complete</span> </div>
                        </div>
                    </div>
                </div>
@Html.Action("CourseListByInstructor", "InstructorAnalysis")
            </div>
        </div>
    </div>
</div>

MyElearningProject/Views/InstructorAnalysis/InstructorPanelPartial.cshtml
@model List<MyElearningProject.DAL.Entities.Instructor>
    @foreach (var item in Model)
    {
<div class="col-lg-4 col-xlg-3 col-md-5">
    <!-- Column -->
    <div class="card">
        <img class="card-img-top" src="@item.CoverImage" alt="Card image cap">
        <div class="card-block little-profile text-center">
            <div class="pro-img"><img src="@item.ImageUrl" alt="user" /></div>
            <h3 class="m-b-0">@item.Name @item.Surname</h3>
            <p>@item.Title</p>
            <a href="javascript:void(0)" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded">Follow</a>
            <div class="row text-center m-t-20">
                <div class="col-lg-4 col-md-4 m-t-20">
                    <h3 class="m-b-0 font-light">@ViewBag.courseCount</h3><small>Kurs Sayısı</small>
                </div>
                <div class="col-lg-4 col-md-4 m-t-20">
                    <h3 class="m-b-0 font-light">@ViewBag.commentCount</h3><small>Yorum Sayısı</small>
                </div>
                <div class="col-lg-4 col-md-4 m-t-20">
                    <h3 class="m-b-0 font-light">6035</h3><small>Following</small>
                </div>
            </div>
        </div>
    </div>
    <!-- Column -->
    
</div>

    }