MyElearningProject/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyElearningProject.Controllers
{
    public class AdminLayoutController : Controller
    {
        // GET: AdminLayout
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }
        public PartialViewResult PartialScript()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialRowPageTitle()
        {
            return PartialView();
        }
        public PartialViewResult PartialPreloader()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialRow()
        {
            return PartialView();
        }
    }
}

MyElearningProject/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead","AdminLayout")
<body class="fix-header fix-sidebar card-no-border">
@Html.Action("PartialPreloader","AdminLayout")
    <div id="main-wrapper">
@Html.Action("PartialNavbar","AdminLayout")       
@Html.Action("PartialSidebar","AdminLayout")
        <div class="page-wrapper">
            <div class="container-fluid">
                @Html.Action("PartialRowPageTitle", "AdminLayout")
                @RenderBody()
@Html.Action("PartialRow","AdminLayout")

            </div>
        </div>
    </div>
@Html.Action("PartialScript","AdminLayout")
</body>
</html>

MyElearningProject/Views/AdminLayout/PartialFooter.cshtml
<footer class="footer">
    © @DateTime.Now.Year | Tüm Hakları Saklıdır. 
</footer>

MyElearningProject/Views/AdminLayout/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/Templates/material-lite-master/assets/images/favicon.png">
    <title>ELearning Admin Paneli</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Templates/material-lite-master/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Templates/material-lite-master/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="~/Templates/material-lite-master/css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

MyElearningProject/Views/AdminLayout/PartialNavbar.cshtml
<header class="topbar">
    <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <img src="~/Templates/material-lite-master/assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text --><span>

                    <!-- Light Logo text -->
                    <img src="~/Templates/material-lite-master/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                </span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto mt-md-0">
                <!-- This is  -->
                <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item hidden-sm-down search-box">
                    <a class="nav-link hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search">
                        <input type="text" class="form-control" placeholder="Search & enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
            <ul class="navbar-nav my-lg-0">
                <!-- ============================================================== -->
                <!-- Profile -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/Templates/material-lite-master/assets/images/users/1.jpg" alt="user" class="profile-pic m-r-10" />Markarn Doe</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

MyElearningProject/Views/AdminLayout/PartialPreloader.cshtml
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
</div>

MyElearningProject/Views/AdminLayout/PartialRow.cshtml
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                This is some text within a card block.
            </div>
        </div>
    </div>
</div>

MyElearningProject/Views/AdminLayout/PartialRowPageTitle.cshtml
<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor m-b-0 m-t-0">Dashboard</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Anasayfa</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
    </div>
    <div class="col-md-7 col-4 align-self-center">
        <a href="https://themewagon.com/themes/material-bootstrap-4-free-admin-template/" class="btn waves-effect waves-light btn-danger pull-right hidden-sm-down">Download Now</a>
    </div>
</div>

MyElearningProject/Views/AdminLayout/PartialScript.cshtml
<script src="~/Templates/material-lite-master/assets/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="~/Templates/material-lite-master/assets/plugins/bootstrap/js/tether.min.js"></script>
<script src="~/Templates/material-lite-master/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="~/Templates/material-lite-master/js/jquery.slimscroll.js"></script>
<!--Wave Effects -->
<script src="~/Templates/material-lite-master/js/waves.js"></script>
<!--Menu sidebar -->
<script src="~/Templates/material-lite-master/js/sidebarmenu.js"></script>
<!--stickey kit -->
<script src="~/Templates/material-lite-master/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
<!--Custom JavaScript -->
<script src="~/Templates/material-lite-master/js/custom.min.js"></script>

MyElearningProject/Views/AdminLayout/PartialSidebar.cshtml
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li>
                    <a class="waves-effect waves-dark" href="index.html" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Anasayfa</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="pages-profile.html" aria-expanded="false"><i class="mdi mdi-account-check"></i><span class="hide-menu">Profil</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Category/Index/" aria-expanded="false"><i class="mdi mdi-table"></i><span class="hide-menu">Kategoriler</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Instructor/Index/" aria-expanded="false"><i class="mdi mdi-school"></i><span class="hide-menu">Eğitmenler</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="map-google.html" aria-expanded="false"><i class="mdi mdi-earth"></i><span class="hide-menu">Google Map</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Course/Index/" aria-expanded="false"><i class="mdi mdi-book-open-variant"></i><span class="hide-menu">Kurslar</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="pages-error-404.html" aria-expanded="false"><i class="mdi mdi-help-circle"></i><span class="hide-menu">Error 404</span></a>
                </li>
            </ul>
            <div class="text-center m-t-30">
                <a href="https://themewagon.com/themes/material-bootstrap-4-free-admin-template/" class="btn waves-effect waves-light btn-warning hidden-md-down">Download Now</a>
            </div>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    <div class="sidebar-footer">
        <!-- item--><a href="" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
        <!-- item--><a href="" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
        <!-- item--><a href="" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
    </div>
    <!-- End Bottom points-->
</aside>